services:
  html-report-server:
    image: ghcr.io/19-mrx-98/report-server:latest
    container_name: reportserver-alpha
    pid: "host"                           # Host-/proc sichtbar
    volumes:
      - /var/static-mountpoint-viewer/output:/data   # Host-Verzeichnis → Container
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"                       # Port 8080 des Containers → Port 8080 des Hos
